### ISSUE TITLE
Cannot open assembly '/home/steam/resonite-headless/Headless/Resonite.exe': No such file or directory.

### ISSUE THREAD

**Issue by NoodleBug** [shadowpanther/resonite-headless#8]
This seems to occur after the .NET 8 update:

```
 Update state (0x61) downloading, progress: 98.02 (1146028015 / 1169208149)
 Update state (0x61) downloading, progress: 99.60 (1164523834 / 1169208149)
 Update state (0x61) downloading, progress: 100.00 (1169208149 / 1169208149)
 Update state (0x81) verifying update, progress: 46.25 (540722463 / 1169208149)
 Update state (0x101) committing, progress: 65.43 (765023481 / 1169208149)
 Update state (0x101) committing, progress: 100.00 (1169208149 / 1169208149)
Success! App '2519830' fully installed.
find: ‘/home/steam/resonite-headless/Data/Assets’: No such file or directory
find: ‘/home/steam/resonite-headless/Data/Cache’: No such file or directory
Cannot open assembly '/home/steam/resonite-headless/Headless/Resonite.exe': No such file or directory.
```

docker-compose.yaml:
```
services:
  resonite:
    image: shadowpanther/resonite-headless:latest
    container_name: resonite-headless
    tty: true
    stdin_open: true
    environment:
      STEAMBETA: headless
      STEAMBETAPASSWORD: ------
      STEAMLOGIN: "------ -------"
    volumes:
      - "./Config:/Config:ro"
      - "./Logs:/Logs"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
```
